# fly.toml app configuration file generated for craite on 2023-08-01T01:13:00-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "craite"
primary_region = "gru"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
